修正职业选择要求
thewakingsands/novice-network pull request #19
Opened 2021-10-08 01:46 UTC by sandtechnology

2021-10-08 02:46 UTC, oott123 requested changes

2021-10-08 02:46 UTC, oott123 commented on docs/before/job.md
> +| 5.0 | 绝枪战士 | 战斗职业等级达到60级且到达格里芬尼亚 |
格里达尼亚

2021-10-08 02:46 UTC, oott123 commented on docs/before/job.md
> +FF14随着版本更新追加了8个新职业，这些职业在创建新角色时都无法选择，除需要接取对应的转职职业任务外，还分别有以下要求：
总觉得怪怪的，因为底下的条件是“接取职业任务”的前置

2021-10-08 02:46 UTC, oott123 commented
@hikarievo 看看咋改比较合适捏

2021-10-08 03:24 UTC, sandtechnology commented on docs/before/job.md
> +FF14随着版本更新追加了8个新职业，这些职业在创建新角色时都无法选择，除需要接取对应的转职职业任务外，还分别有以下要求：
这里我也想不好怎么改 看看有没有更好的解法？

2021-11-08 10:20 UTC, sandtechnology commented
@hikarievo 阿布有时间可以看看吗？已经一个月啦

2021-11-19 06:27 UTC, merged